### ISSUE TITLE
Doubt regarding pulling and merging db

### ISSUE THREAD

**Issue by VLBHAT31** [kinderneutron/kinderneutron-env-init#7]
![Screenshot from 2024-03-27 12-37-02](https://github.com/kinderneutron/kinderneutron-env-init/assets/106856462/28b61fa2-4b8d-4be3-b292-db2400298439)
@kinderasteroid what should i do in this case

**Comment by kinderasteroid** [comment]
@VLBHAT31  make one Branch for Safer side from cuurently where you are working on with
```
git checkout -b <branch-name>
```

then execute 
```
git pull --no-rebase upstream 
```

Let me Know here after the changes

**Comment by VLBHAT31** [comment]
Resolved. Thankyou @kinderasteroid
